version: '3.3'
services:
  # postgres teste
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5437:5432"
    volumes:
      - ./shared/db/migration_docker_test.sql:/docker-entrypoint-initdb.d/migration_docker_test.sql  
  app:
    build: .
    container_name: GVendas
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/app
    links: 
      - database
    depends_on:
      - database

